### PR TITLE
Update to Web API 2

### PR DESCRIPTION
**Pull request by panesofglass**

### CODE REVIEW

**Comment by panesofglass** [comment]
@ChrisMissal this should be ready to publish, though this does not address #2.

**Comment by ChrisMissal** [comment]
It's currently at 0.9.3, this would bring us to 1.0.0, right? (Or do we skip a version to keep them the same?)

**Comment by panesofglass** [comment]
I'd prefer we jump to 2.0, though given the issue with the Jsonp project, I wonder if we shouldn't actually switch to sources rather than compiled assemblies. Or at least offer both options? How hard is it to do that from MyGet? I can add a FAKE build to package the sources if you like. (I'm not well versed in PowerShell or psake).

Sent from Windows Mail

From: Dave Thomas
Sent: ‎Tuesday‎, ‎January‎ ‎28‎, ‎2014 ‎9‎:‎33‎ ‎AM
To: WebApiContrib/WebApiContrib.IoC.Ninject
Cc: Ryan Riley

It's currently at 0.9.3, this would bring us to 1.0.0, right? (Or do we skip a version to keep them the same?)

**Comment by ChrisMissal** [comment]
I think all we need is another .nuspec file, but I'd have to check to be
sure. And if you want to move to FAKE, I'm all for it!

On Tue, Jan 28, 2014 at 9:53 AM, Ryan Riley notifications@github.comwrote:

> I'd prefer we jump to 2.0, though given the issue with the Jsonp project,
> I wonder if we shouldn't actually switch to sources rather than compiled
> assemblies. Or at least offer both options? How hard is it to do that from
> MyGet? I can add a FAKE build to package the sources if you like. (I'm not
> well versed in PowerShell or psake).
> 
> Sent from Windows Mail
> 
> From: Dave Thomas
> Sent: Tuesday, January 28, 2014 9:33 AM
> To: WebApiContrib/WebApiContrib.IoC.Ninject
> Cc: Ryan Riley
> 
> It's currently at 0.9.3, this would bring us to 1.0.0, right? (Or do we
> skip a version to keep them the same?)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/WebApiContrib/WebApiContrib.IoC.Ninject/pull/3#issuecomment-33491274
> .

## 

_Chris Missal | *Senior Consultant | *Headspring_

**Pull request merged**
